/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryChip: typeof import('./src/components/basics/CategoryChip.vue')['default']
    HomeCategoriesBanner: typeof import('./src/components/homepage/HomeCategoriesBanner.vue')['default']
    HomePartnerSection: typeof import('./src/components/homepage/HomePartnerSection.vue')['default']
    HomeSearchBox: typeof import('./src/components/homepage/HomeSearchBox.vue')['default']
    IconFood: typeof import('./src/components/icons/IconFood.vue')['default']
    IconMusic: typeof import('./src/components/icons/IconMusic.vue')['default']
    IconPhoto: typeof import('./src/components/icons/IconPhoto.vue')['default']
    IconPlace: typeof import('./src/components/icons/IconPlace.vue')['default']
    PartnerThumbnail: typeof import('./src/components/partner/PartnerThumbnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SgiltChip: typeof import('./src/components/basics/SgiltChip.vue')['default']
    SgiltSelect: typeof import('./src/components/basics/SgiltSelect.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
