services:
  sgilt-keycloak-db:
    image: postgres:17
    container_name: sgilt-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    networks:
      - sgilt-dev-net

  sgilt-keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: sgilt-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://sgilt-keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "5028:8080"
    depends_on:
      - sgilt-keycloak-db
    volumes:
      - ../sgilt-keycloak/:/opt/keycloak/data/import
      - ../sgilt-keycloak/theme:/opt/keycloak/themes/sgilt-theme
    networks:
      - sgilt-dev-net

  sgilt-smtp-bridge:
    image: sgilt-smtp-bridge
    container_name: sgilt-smtp-bridge
    environment:
      - MAILER_URL=http://host.docker.internal:5030/api/v1/mail
    build:
      context: ../sgilt-smtp-bridge
    networks:
      - sgilt-dev-net

  sgilt-mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: sgilt-mailhog
    ports:
      - "1026:1025" # SMTP
      - "5125:8025" # Web UI

  sgilt-db:
    image: postgres:17
    container_name: sgilt-db
    environment:
      POSTGRES_DB: sgilt
      POSTGRES_USER: sgilt
      POSTGRES_PASSWORD: sgilt
    ports:
      - "5432:5432"
    volumes:
      - sgilt_pgdata:/var/lib/postgresql/data
    networks:
      - sgilt-dev-net

networks:
  sgilt-dev-net:
    driver: bridge

volumes:
  core_pgdata:
  keycloak_pgdata:
  sgilt_pgdata:
