server:
  port: 5080

spring:
  application:
    name: sgilt-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: onboarding-public
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/onboarding/**

            - id: confirmation-public
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/confirmation

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://host.docker.internal:5028/realms/sgilt}
