server:
  port: 5080

spring:
  application:
    name: sgilt-gateway
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_SIZE_MB:10}MB
      max-request-size: ${MAX_UPLOAD_SIZE_MB:10}MB
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: onboarding-public
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/onboarding/**

            - id: confirmation-public
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/confirmation

            - id: prestataires-public
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/prestataires/**

            - id: users-private
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/users/**

            - id: user-private
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/user/**

            - id: reservations-feed
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/reservations/*/feed/**

            - id: pro-private
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/pro/**

            - id: admin-private
              uri: ${BACK_URL:http://localhost:5027}
              predicates:
                - Path=/api/v1/admin/**

            - id: notifications-private
              uri: ${NOTIFICATIONS_URL:http://localhost:5031}
              predicates:
                - Path=/api/v1/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:5028/realms/sgilt}
