# docker-compose.base.yml

networks:
  sgilt-network:
    name: sgilt-network-${ENV}

volumes:
  sgilt_keycloak_pgdata:
    name: sgilt_keycloak_pgdata_${ENV}
  sgilt_core_pgdata:
    name: sgilt_core_pgdata_${ENV}