# docker-compose.mailer.yml

services:
  # =====================
  # SGILT-MAILER (Spring Boot)
  # =====================
  sgilt-mailer:
    image: ghcr.io/franzk/sgilt/sgilt-mailer:${SGILT_MAILER_VERSION}
    container_name: sgilt-mailer-${ENV}
    pull_policy: always
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_SSL: ${SMTP_SSL}
    networks:
      - sgilt-network
    restart: unless-stopped

  # =====================
  # SGILT-SMTP-BRIDGE (Node.js)
  # =====================
  sgilt-smtp-bridge:
    image: ghcr.io/franzk/sgilt/sgilt-smtp-bridge:${SGILT_SMTP_BRIDGE_VERSION}
    container_name: sgilt-smtp-bridge-${ENV}
    pull_policy: always
    environment:
      MAILER_URL: http://sgilt-mailer:8080
    networks:
      - sgilt-network
    restart: unless-stopped

networks:
  sgilt-network:
    name: sgilt-network-${ENV}