# docker-compose.front.yml

services:
  # =====================
  # SGILT-FRONT (Nuxt SSR)
  # =====================
  sgilt-front:
    image: ghcr.io/franzk/sgilt/sgilt-front:${SGILT_FRONT_VERSION}
    container_name: sgilt-front-${ENV}
    pull_policy: always
    environment:
      ENV: ${ENV}
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
      NUXT_PUBLIC_API_URL: ${API_URL}
      NUXT_PUBLIC_KC_URL: ${AUTH_URL}
      NUXT_PUBLIC_KC_REALM: ${KC_REALM}
      NUXT_PUBLIC_KC_CLIENT_ID: ${KC_FRONT_CLIENT_ID}
    depends_on:
      - sgilt-keycloak
    networks:
      - sgilt-network
    restart: unless-stopped

  # =====================
  # NGINX FRONT
  # =====================
  nginx-front:
    image: nginx:alpine
    container_name: nginx-front-${ENV}
    ports:
      - "${NGINX_FRONT_PORT}:443"
    volumes:
      - ./nginx/front.conf.template:/etc/nginx/templates/default.conf.template:ro
      - /etc/ssl/sgilt:/etc/ssl/sgilt:ro
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    depends_on:
      - sgilt-front
    networks:
      - sgilt-network
    restart: unless-stopped

networks:
  sgilt-network:
    name: sgilt-network-${ENV}